In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### SEntences

sent = [
    'The glass of milk',
    'The glass of Juice',
    'The cup of tea',
    'I am a good boy',
    'I am a good developer',
    'I am a good developer',
    'Understand the meaning of words',
    'Your videos are good',
]

In [4]:
sent

['The glass of milk',
 'The glass of Juice',
 'The cup of tea',
 'I am a good boy',
 'I am a good developer',
 'I am a good developer',
 'Understand the meaning of words',
 'Your videos are good']

In [5]:
## Define the vocabulary words

voc_size = 10000


In [6]:
## One hot Representation

one_hot_repre = [one_hot(words,voc_size) for words in sent]
one_hot_repre

    

[[8333, 1381, 2415, 1189],
 [8333, 1381, 2415, 9711],
 [8333, 8908, 2415, 4580],
 [7024, 5933, 2152, 9777, 5855],
 [7024, 5933, 2152, 9777, 4114],
 [7024, 5933, 2152, 9777, 4114],
 [3235, 8333, 6056, 2415, 7484],
 [3336, 959, 1162, 9777]]

In [8]:
## word  embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 8 
embedded_docs = pad_sequences(one_hot_repre,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 8333, 1381, 2415, 1189],
       [   0,    0,    0,    0, 8333, 1381, 2415, 9711],
       [   0,    0,    0,    0, 8333, 8908, 2415, 4580],
       [   0,    0,    0, 7024, 5933, 2152, 9777, 5855],
       [   0,    0,    0, 7024, 5933, 2152, 9777, 4114],
       [   0,    0,    0, 7024, 5933, 2152, 9777, 4114],
       [   0,    0,    0, 3235, 8333, 6056, 2415, 7484],
       [   0,    0,    0,    0, 3336,  959, 1162, 9777]])

In [11]:
# feature Representation

dim = 10 

In [12]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 409ms/step


array([[[ 0.03044024,  0.02006564,  0.00015533,  0.009558  ,
         -0.03660792,  0.03212324,  0.02074495, -0.01172236,
         -0.01358556, -0.04511023],
        [ 0.03044024,  0.02006564,  0.00015533,  0.009558  ,
         -0.03660792,  0.03212324,  0.02074495, -0.01172236,
         -0.01358556, -0.04511023],
        [ 0.03044024,  0.02006564,  0.00015533,  0.009558  ,
         -0.03660792,  0.03212324,  0.02074495, -0.01172236,
         -0.01358556, -0.04511023],
        [ 0.03044024,  0.02006564,  0.00015533,  0.009558  ,
         -0.03660792,  0.03212324,  0.02074495, -0.01172236,
         -0.01358556, -0.04511023],
        [-0.02508702,  0.01603602, -0.04701871, -0.0139125 ,
         -0.00636628,  0.02163669,  0.01651229,  0.01357988,
         -0.00096762, -0.01999525],
        [-0.04091221,  0.03472464, -0.01130644,  0.0182649 ,
          0.00739504, -0.04004062,  0.04716447, -0.03073124,
          0.00784934, -0.02733555],
        [-0.02141132,  0.00792418, -0.0459176 , -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 8333, 1381, 2415, 1189])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 110ms/step


array([[ 0.03044024,  0.02006564,  0.00015533,  0.009558  , -0.03660792,
         0.03212324,  0.02074495, -0.01172236, -0.01358556, -0.04511023],
       [ 0.03044024,  0.02006564,  0.00015533,  0.009558  , -0.03660792,
         0.03212324,  0.02074495, -0.01172236, -0.01358556, -0.04511023],
       [ 0.03044024,  0.02006564,  0.00015533,  0.009558  , -0.03660792,
         0.03212324,  0.02074495, -0.01172236, -0.01358556, -0.04511023],
       [ 0.03044024,  0.02006564,  0.00015533,  0.009558  , -0.03660792,
         0.03212324,  0.02074495, -0.01172236, -0.01358556, -0.04511023],
       [-0.02508702,  0.01603602, -0.04701871, -0.0139125 , -0.00636628,
         0.02163669,  0.01651229,  0.01357988, -0.00096762, -0.01999525],
       [-0.04091221,  0.03472464, -0.01130644,  0.0182649 ,  0.00739504,
        -0.04004062,  0.04716447, -0.03073124,  0.00784934, -0.02733555],
       [-0.02141132,  0.00792418, -0.0459176 , -0.01434652, -0.02570109,
         0.03223789,  0.00888991,  0.0345226 